In [1]:
import pandas as pd
df=pd.read_csv("Finance_data.csv")
df.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [2]:
df.columns

Index(['gender', 'age', 'Investment_Avenues', 'Mutual_Funds', 'Equity_Market',
       'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold',
       'Stock_Marktet', 'Factor', 'Objective', 'Purpose', 'Duration',
       'Invest_Monitor', 'Expect', 'Avenue',
       'What are your savings objectives?', 'Reason_Equity', 'Reason_Mutual',
       'Reason_Bonds', 'Reason_FD', 'Source'],
      dtype='str')

In [3]:
df.shape

(40, 24)

In [5]:
df.iloc[:10]

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet
5,Female,24,No,7,5,4,6,3,1,2,...,1-3 years,Daily,30%-40%,Mutual Fund,Retirement Plan,Liquidity,Fund Diversification,Safe Investment,Risk Free,Internet
6,Female,27,Yes,3,6,4,2,5,1,7,...,3-5 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,High Interest Rates,Financial Consultants
7,Male,21,Yes,2,3,7,4,6,1,5,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
8,Male,35,Yes,2,4,7,5,3,1,6,...,1-3 years,Weekly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Fund Diversification,Safe Investment,Fixed Returns,Television
9,Male,31,Yes,1,3,7,4,5,2,6,...,3-5 years,Monthly,30%-40%,Fixed Deposits,Retirement Plan,Capital Appreciation,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines

In [6]:
df.iloc[5:15,2:10]

,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
5,No,7,5,4,6,3,1,2
6,Yes,3,6,4,2,5,1,7
7,Yes,2,3,7,4,6,1,5
8,Yes,2,4,7,5,3,1,6
9,Yes,1,3,7,4,5,2,6
10,Yes,2,4,7,5,3,1,6
11,Yes,2,5,7,6,3,1,4
12,No,1,2,3,4,5,6,7
13,Yes,2,3,7,4,5,1,6
14,Yes,2,3,7,5,4,1,6

In [11]:
df.iloc[:, 3:10]

,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
0,1,2,5,3,7,6,4
1,4,3,2,1,5,6,7
2,3,6,4,2,5,1,7
3,2,1,3,7,6,4,5
4,2,1,3,6,4,5,7
5,7,5,4,6,3,1,2
6,3,6,4,2,5,1,7
7,2,3,7,4,6,1,5
8,2,4,7,5,3,1,6
9,1,3,7,4,5,2,6
10,2,4,7,5,3,1,6
11,2,5,7,6,3,1,4
12,1,2,3,4,5,6,7
13,2,3,7,4,5,1,6
14,2,3,7,5,4,1,6
15,2,3,7,5,4,1,6
16,3,2,7,5,4,1,6
17,3,2,7,4,5,1,6
18,3,2,7,4,5,1,6
19,3,4,6,5,1,2,7
20,2,4,7,5,3,1,6
21,2,4,5,6,3,1,7
22,3,4,6,5,2,1,7
23,2,4,6,5,3,1,7
24,2,3,7,5,4,1,6
25,3,4,7,5,1,2,6
26,3,4,6,5,1,2,7
27,2,3,7,6,4,1,5
28,2,3,6,5,1,4,7
29,5,4,3,2,7,1,6
30,4,5,1,2,7,3,6
31,2,4,7,6,3,1,5
32,2,4,7,5,1,3,6
33,2,3,6,4,1,5,7
34,2,3,6,5,4,1,7
35,1,4,6,5,3,2,7
36,2,4,7,5,1,3,6
37,5,4,7,6,1,2,3
38,2,4,7,5,3,1,6
39,4,3,5,7,2,1,6

In [15]:
df.loc[10:20,["gender","age","Avenue","Duration","Expect"]]

    gender  age          Avenue   Duration   Expect
10  Female   35     Mutual Fund  3-5 years  20%-30%
11    Male   29     Mutual Fund  1-3 years  20%-30%
12  Female   21     Mutual Fund  1-3 years  20%-30%
13  Female   28     Mutual Fund  1-3 years  20%-30%
14  Female   25  Fixed Deposits  1-3 years  20%-30%
15    Male   27     Mutual Fund  1-3 years  20%-30%
16  Female   28  Fixed Deposits  1-3 years  20%-30%
17    Male   27     Mutual Fund  1-3 years  20%-30%
18    Male   29     Mutual Fund  1-3 years  20%-30%
19    Male   26  Fixed Deposits  3-5 years  20%-30%
20    Male   29     Mutual Fund  3-5 years  20%-30%

In [20]:
df.iloc[-10:,:]

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
30,Male,27,Yes,4,5,1,2,7,3,6,...,1-3 years,Monthly,10%-20%,Mutual Fund,Education,Capital Appreciation,Tax Benefits,Safe Investment,Fixed Returns,Television
31,Female,31,Yes,2,4,7,6,3,1,5,...,3-5 years,Monthly,20%-30%,Fixed Deposits,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns,Financial Consultants
32,Male,27,Yes,2,4,7,5,1,3,6,...,3-5 years,Monthly,30%-40%,Equity,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines
33,Male,26,Yes,2,3,6,4,1,5,7,...,1-3 years,Monthly,20%-30%,Fixed Deposits,Education,Dividend,Better Returns,Safe Investment,Risk Free,Newspapers and Magazines
34,Male,27,Yes,2,3,6,5,4,1,7,...,1-3 years,Weekly,20%-30%,Mutual Fund,Health Care,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Financial Consultants
35,Male,30,Yes,1,4,6,5,3,2,7,...,3-5 years,Monthly,20%-30%,Fixed Deposits,Health Care,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns,Financial Consultants
36,Male,30,Yes,2,4,7,5,1,3,6,...,1-3 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
37,Male,25,Yes,5,4,7,6,1,2,3,...,3-5 years,Monthly,30%-40%,Public Provident Fund,Health Care,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Financial Consultants
38,Male,31,Yes,2,4,7,5,3,1,6,...,1-3 years,Weekly,20%-30%,Equity,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines
39,Male,29,Yes,4,3,5,7,2,1,6,...,3-5 years,Monthly,20%-30%,Fixed Deposits,Retirement Plan,Dividend,Better Returns,Safe Investment,Fixed Returns,Financial Consultants

In [21]:
df.iloc[::2]

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet
6,Female,27,Yes,3,6,4,2,5,1,7,...,3-5 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,High Interest Rates,Financial Consultants
8,Male,35,Yes,2,4,7,5,3,1,6,...,1-3 years,Weekly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Fund Diversification,Safe Investment,Fixed Returns,Television
10,Female,35,Yes,2,4,7,5,3,1,6,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Financial Consultants
12,Female,21,No,1,2,3,4,5,6,7,...,1-3 years,Weekly,20%-30%,Mutual Fund,Education,Dividend,Better Returns,Safe Investment,Risk Free,Internet
14,Female,25,Yes,2,3,7,5,4,1,6,...,1-3 years,Monthly,20%-30%,Fixed Deposits,Health Care,Dividend,Better Returns,Assured Returns,Risk Free,Financial Consultants
16,Female,28,Yes,3,2,7,5,4,1,6,...,1-3 years,Monthly,20%-30%,Fixed Deposits,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Risk Free,Television
18,Male,29,Yes,3,2,7,4,5,1,6,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
20,Male,29,Yes,2,4,7,5,3,1,6,...,3-5 years,Weekly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns,Financial Consultants
22,Male,27,Yes,3,4,6,5,2,1,7,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Financial Consultants
24,Female,26,Yes,2,3,7,5,4,1,6,...,3-5 years,Monthly,30%-40%,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
26,Male,26,Yes,3,4,6,5,1,2,7,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Dividend,Fund Diversification,Assured Returns,Fixed Returns,Financial Consultants
28,Male,29,Yes,2,3,6,5,1,4,7,...,1-3 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Television
30,Male,27,Yes,4,5,1,2,7,3,6,...,1-3 years,Monthly,10%-20%,Mutual Fund,Education,Capital Appreciation,Tax Benefits,Safe Investment,Fixed Returns,Television
32,Male,27,Yes,2,4,7,5,1,3,6,...,3-5 years,Monthly,30%-40%,Equity,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines
34,Male,27,Yes,2,3,6,5,4,1,7,...,1-3 years,Weekly,20%-30%,Mutual Fund,Health Care,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Financial Consultants
36,Male,30,Yes,2,4,7,5,1,3,6,...,1-3 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
38,Male,31,Yes,2,4,7,5,3,1,6,...,1-3 years,Weekly,20%-30%,Equity,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines